require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InvolvementsController do

  # This should return the minimal set of attributes required to create a valid
  # Involvement. As you add validations to Involvement, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "allow_appointment" => "false" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InvolvementsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all involvements as @involvements" do
      involvement = Involvement.create! valid_attributes
      get :index, {}, valid_session
      assigns(:involvements).should eq([involvement])
    end
  end

  describe "GET show" do
    it "assigns the requested involvement as @involvement" do
      involvement = Involvement.create! valid_attributes
      get :show, {:id => involvement.to_param}, valid_session
      assigns(:involvement).should eq(involvement)
    end
  end

  describe "GET new" do
    it "assigns a new involvement as @involvement" do
      get :new, {}, valid_session
      assigns(:involvement).should be_a_new(Involvement)
    end
  end

  describe "GET edit" do
    it "assigns the requested involvement as @involvement" do
      involvement = Involvement.create! valid_attributes
      get :edit, {:id => involvement.to_param}, valid_session
      assigns(:involvement).should eq(involvement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Involvement" do
        expect {
          post :create, {:involvement => valid_attributes}, valid_session
        }.to change(Involvement, :count).by(1)
      end

      it "assigns a newly created involvement as @involvement" do
        post :create, {:involvement => valid_attributes}, valid_session
        assigns(:involvement).should be_a(Involvement)
        assigns(:involvement).should be_persisted
      end

      it "redirects to the created involvement" do
        post :create, {:involvement => valid_attributes}, valid_session
        response.should redirect_to(Involvement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved involvement as @involvement" do
        # Trigger the behavior that occurs when invalid params are submitted
        Involvement.any_instance.stub(:save).and_return(false)
        post :create, {:involvement => { "allow_appointment" => "invalid value" }}, valid_session
        assigns(:involvement).should be_a_new(Involvement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Involvement.any_instance.stub(:save).and_return(false)
        post :create, {:involvement => { "allow_appointment" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested involvement" do
        involvement = Involvement.create! valid_attributes
        # Assuming there are no other involvements in the database, this
        # specifies that the Involvement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Involvement.any_instance.should_receive(:update_attributes).with({ "allow_appointment" => "false" })
        put :update, {:id => involvement.to_param, :involvement => { "allow_appointment" => "false" }}, valid_session
      end

      it "assigns the requested involvement as @involvement" do
        involvement = Involvement.create! valid_attributes
        put :update, {:id => involvement.to_param, :involvement => valid_attributes}, valid_session
        assigns(:involvement).should eq(involvement)
      end

      it "redirects to the involvement" do
        involvement = Involvement.create! valid_attributes
        put :update, {:id => involvement.to_param, :involvement => valid_attributes}, valid_session
        response.should redirect_to(involvement)
      end
    end

    describe "with invalid params" do
      it "assigns the involvement as @involvement" do
        involvement = Involvement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Involvement.any_instance.stub(:save).and_return(false)
        put :update, {:id => involvement.to_param, :involvement => { "allow_appointment" => "invalid value" }}, valid_session
        assigns(:involvement).should eq(involvement)
      end

      it "re-renders the 'edit' template" do
        involvement = Involvement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Involvement.any_instance.stub(:save).and_return(false)
        put :update, {:id => involvement.to_param, :involvement => { "allow_appointment" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested involvement" do
      involvement = Involvement.create! valid_attributes
      expect {
        delete :destroy, {:id => involvement.to_param}, valid_session
      }.to change(Involvement, :count).by(-1)
    end

    it "redirects to the involvements list" do
      involvement = Involvement.create! valid_attributes
      delete :destroy, {:id => involvement.to_param}, valid_session
      response.should redirect_to(involvements_url)
    end
  end

end
